services:

    documentlanding.demo_manager:
        class: DocumentLanding\SdkDemoBundle\Service\SdkDemoManager
        public: true
        tags:
            - { name: kernel.event_subscriber  }
        arguments: [ %DocumentLandingSdkBundleConfig%, @mailer, @doctrine.orm.entity_manager ]